# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 569a56614c676c18f5bd572efa06d9a76b03ee65f0ee3ee907d06edb6174cd5109c6e6a8897a085506b2088f3765f116e3e1e4c4a829d1b692351c258dfbf0fc

test:
  secret_key_base: e8fbb188b685d9bd285a71d36259814a5f98e97c78a5cbed90abb51a3bdfb16d41eaaea8d8f5ed1e90d5476b22b13bf745c3fbad0c4bf1f60b59ea896ffd2f14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
